version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
      args:
        BUILD_TARGET: local
    ports:
      - "3000:3000"
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: /bin/bash -c "bundle exec rails server -b 0.0.0.0 -p 4000 -e production"
    ports:
      - "4000:4000"
