source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.5"

# Bundle edge Rails instead: gem "rails", github: "rails/rails"
gem "rails", "~> 6.0.0"
gem "mysql2", ">= 0.4.4"
gem "puma", "~> 3.12"
gem "nokogiri"
gem "rest-client"
gem "config"
gem "figaro"
gem "kaminari"
gem "jbuilder", "~> 2.7"
gem "whenever", require: false
gem "devise_token_auth"
gem "bcrypt", "~> 3.1.7"
gem "bootsnap", ">= 1.4.2", require: false
gem "rack-cors"

group :test do
  gem "factory_girl_rails"
  gem "shoulda-matchers"
  gem "faker"
  gem "database_cleaner"
end

group :development, :test do
  gem "rspec-rails"
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rubocop", "~> 0.76.0", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-checkstyle_formatter", require: false
  gem "rubocop-rspec", require: false
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
