// Code generated by "stringer -type=Level"; DO NOT EDIT.

package logs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownLevel-0]
	_ = x[DebugLevel-1]
	_ = x[InfoLevel-2]
	_ = x[WarnLevel-3]
	_ = x[ErrorLevel-4]
}

const _Level_name = "UnknownLevelDebugLevelInfoLevelWarnLevelErrorLevel"

var _Level_index = [...]uint8{0, 12, 22, 31, 40, 50}

func (i Level) String() string {
	if i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
